name: dhmqc-dev
channels:
  - conda-forge
dependencies:
  - gdal==3.6 # pin due to ogr.Open() behavior
  - owslib
  - psycopg2
  - numpy
  - scipy
  - laspy>=2.0
  # Consider reverting to pip + pip-installed laszip in case of problems
  - lazrs-python
  # For testing only
  - pytest
