name: dhmqc-dev
channels:
  - conda-forge
dependencies:
  - gdal
  - owslib
  - psycopg2
  - numpy
  - scipy
  - laspy>=2.0
  # Consider reverting to pip + pip-installed laszip in case of problems
  - lazrs-python
  - libgcc  # [win]
  # For testing only
  - pytest
