name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        # Will activate a mostly-empty env called "test"
    - name: Install dependencies
      run: |
        # Pre-install environment state
        conda info --quiet
        # Install dependencies to base environment due to lack of persistence between workflow steps
        conda install --quiet -v --yes --name base --channel conda-forge python=${{ matrix.python-version }} gdal owslib psycopg2 numpy scipy pandas laspy=1.7 laszip lastools nose
        # Post-install environment state
        conda info --quiet
    - name: Build C/C++ components
      run: |
        python src/build/build.py -v -x64 -force -cc gcc -cxx g++
    - name: Test with nose
      shell: cmd /C CALL {0}
      run: >-
        conda info --quiet && echo %PATH% && dir C:\Miniconda3\envs\test\Scripts && nosetests tests.py -v
